USE OutpatientClinicDoctorDB
IF OBJECT_ID('tb_TCM') IS NOT NULL
DROP TABLE tb_TCM;
GO
CREATE TABLE tb_TCM
	(No
		VARCHAR(50)
	,Date
		DATE
	,HealthCardNo
		VARCHAR(50)
		CONSTRAINT fk_TCMList_HealthCardNo
		FOREIGN KEY (HealthCardNo)
		REFERENCES tb_Patient(HealthCardNo)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
	,DoctorNo
		VARCHAR(50)
		CONSTRAINT fk_TCMList_DoctorNo
		FOREIGN KEY (DoctorNo)
		REFERENCES tb_Doctor(No)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
	,HerbNo
		INT
		CONSTRAINT fk_TCM_HerbNo
		FOREIGN KEY (HerbNo)
		REFERENCES tb_Herb(No)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
	,Usage
		INT)